language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

# This is for make code abstract, facilitating copy-pasting.
env:
  GITHUB_REPOSITORY=drupal7-moopapi DRUPAL_VERSION=7.x DRUPAL_MODULE=moopapi

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 - cd ..
 # --no-cache is must-have due to http://drupal.org/node/1630220
 - drush dl drupal-$DRUPAL_VERSION --no-cache
 # Discover newly downloaded directory.
 - ls -la
 - cd drupal-*
 # make sure we are inside Drupal root.
 - ls -la
 # Install Drupal.
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en simpletest --yes
 - cp -R ../$GITHUB_REPOSITORY sites/all/modules/$DRUPAL_MODULE
 - drush en $DRUPAL_MODULE --yes
 # To make test file discoverable.
 #- ls -la
 # Up to Drupal root level.
 #- cd ../../../../../
 # DEBUG
 #- ls -la
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 #- drush vset simpletest_verbose FALSE --yes
 - drush vset simpletest_verbose TRUE --yes

script: php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.13/bin/php --url 'http://127.0.0.1:8080' --verbose --file sites/all/modules/$DRUPAL_MODULE/$DRUPAL_MODULE.test
 #drush test-run --xml --file=sites/all/modules/moopapi/core/simpletest.test --uri=http://127.0.0.1:8080

after_script:
 #- ls sites/default/files -la
